3 4
matt-visentin/myFlix-client-1 pull request #1
Opened 2023-08-12 10:02 UTC by matt-visentin

2023-08-12 18:10 UTC, stratospherique requested changes

2023-08-12 18:10 UTC, stratospherique commented on src/components/movie-card/movie-card.jsx
> +MovieCard.PropTypes = {
This line is causing a runtime error in the browser console(check it). It's `ComponentName.propTypes`

2023-08-13 10:31 UTC, matt-visentin commented
I see what you mean. I corrected it.

2023-08-14 17:52 UTC, stratospherique requested changes

2023-08-14 19:50 UTC, matt-visentin commented on src/components/movie-card/movie-card.jsx
> +    }).isRequired,
Sure, thank you. I changed that now.

2023-08-14 19:50 UTC, matt-visentin commented on src/components/movie-view/movie-view.jsx
> +    }).isRequired,
Sure, thank you. I changed that now.

2023-08-14 19:51 UTC, matt-visentin commented on src/components/movie-view/movie-view.jsx
> +
The image tag seems not to render the image. I also tried with changing "image" with "imagePath" as I have it in on my db but didn't seem to be effective.

2023-08-14 23:22 UTC, stratospherique requested changes

2023-08-18 09:04 UTC, merged